### ISSUE TITLE
solutions too optimised, urgent need to throttle solution speed before they break the space-time continuum and end reality

### ISSUE THREAD

**Issue by RoguedBear** [codeSpicer/LeetCode-solutions#1]
solutions are toooo fast. need to slow them down, just like how they did in Ghost Of Tsushima
https://screenrant.com/ghost-of-tsushima-load-times-fast-slowed-down/

---
![](https://media.tenor.com/WpLMwvtNBz4AAAAS/starwars-sos.gif)

**Comment by codeSpicer** [comment]
![image](https://user-images.githubusercontent.com/77925154/194856127-9f528319-13f2-4616-ba7a-168ffaa22f3d.png)

**Comment by RoguedBear** [comment]
ok bro 😔🫠
